### ISSUE TITLE
Doubt

### ISSUE THREAD

**Issue by linoxguy** [MaherGebrail/arp_Guard#1]
Can we use the scripts and create an Android app??

**Comment by MaherGebrail** [comment]
This scripts made for linux, as it mainly depends on [arptaples] rules .. and since it's also made of python ...  you'll need a lot of manipulation to do so ... but i guess it's better to take it's idea and start from scratch in a better suitable way for android.

**Comment by linoxguy** [comment]
Sir, can you please tell me how to make changes in python code so that I
get an alert notification in kali when someone try to do arp poisoning
Thank you🙏

**Comment by MaherGebrail** [comment]
in [ExpressVpn_Monitor_Status](https://github.com/MaherGebrail/ExpressVpn_Monitor_Status) repo ... you will find an example at **ExpressVpn_pyqt.py** of **plyer lib** to do so.
