### ISSUE TITLE
Request

### ISSUE THREAD

**Issue by linoxguy** [MaherGebrail/arp_Guard#2]
Sir, if you don't mind can your please explain the python script in detail, either by making a video or atleast by using word, and share  it so that it would be very helpful. 
Thank you 🙏

**Comment by MaherGebrail** [comment]
Hi @linoxguy, i believe the script is clear enough from comments and doc strings .. so the only way to really explain things in details is to explain a little bit of network, arptaples , ManInTheMiddle attack concept and python.

Which will take time that i really don't have right now.
