### ISSUE TITLE
Internet issue

### ISSUE THREAD

**Issue by linoxguy** [MaherGebrail/arp_Guard#3]
Sir, the code is working and it is defending from arp poisoning attack but, after the attack is prevented, I am unble to access internet on the victim machine, can you please solve this issue 🙏
Thank you

**Comment by MaherGebrail** [comment]
Hi @linoxguy  ... you can see the output of ( arptables -L ) command, you will find that the script only blocks the arp requests from the attacker ip .. so you are even allowed to ping the attacker from the victim device.

I believe that the problem might be caused from another issue unrelated to the script.
